# Port aplikacije zadnjeg dela:
server.port = 8080

# Podešavanje konekcije sa bazom podataka:
spring.datasource.driverClassName = org.postgresql.Driver
spring.datasource.initialization-mode = always
spring.datasource.platform = postgres
spring.datasource.url = jdbc:postgresql://localhost:5432/isa-tim8-2023-db
spring.datasource.username = postgres
spring.datasource.password = password

spring.jpa.hibernate.ddl-auto = create-drop

spring.jpa.show-sql = true

spring.jpa.properties.hibernate.format_sql = true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL95Dialect

spring.jpa.open-in-view = false

# Podešavanje slanja elektronskih poruka:
spring.mail.host = smtp.gmail.com
spring.mail.username = isa.tim30.darijan.micic.2022.2023
spring.mail.password = sccsphppulilmmsd
spring.mail.port = 587
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
# Dodao sam naredne dve linije kako bih omogucio slanje elektronske poruke.
# REFERENCE: https://stackoverflow.com/questions/16115453/javamail-could-not-convert-socket-to-tls-gmail
spring.mail.properties.mail.smtp.ssl.trust = smtp.gmail.com smtp.uns.ac.rs
spring.mail.properties.mail.smtp.ssl.protocols = TLSv1.2
